# This file has to be manually loaded on my cloud server if modified.
# curl -L  > docker-compose.yml

version: "3"

services:

  # The Website
  joshuapjacob.com:
    container_name: joshuapjacob.com
    image: index.docker.io/joshuapjacob/joshuapjacob.com:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

  # Automatically reloads the website container if new image is available.
  # Checks for updates on the DockerHub repo the every 5 minutes.
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/joshuapjacob/.docker/config.json:/config.json
    command: --debug --interval 300