server {

    listen 80;
    listen [::]:80;

    server_name joshuapjacob.com www.joshuapjacob.com;

    # Certbot Validation
    location /.well-known/acme-challenge {
        allow all;
        root /var/www/letsencrypt;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

}